Rewrite home page as a client component
zetkin/lyra pull request #98
Opened 2024-06-18 19:52 UTC by henrycatalinismith

How about this?

* No server-side data access outside the REST API.
* No dodgy-looking Next.js 14 upgrade.
* No interesting new Next.js routing features.

Just a good old fashioned bit of client-side rendering!

<img width="444" src="https://github.com/zetkin/lyra/assets/566159/46e27867-f85f-4ec8-8081-a0407823ac11" />

2024-06-27 10:47 UTC, WULCAN requested changes
Thank you, this is excellent work. I just want us to clean up the killed code too. See the thread on `src/app/page.tsx`.

We recently decided that there is no need to refactor everything to client components but if you still want to merge this, I see no harm in it and I don't believe @amerharb or @richardolsson would object to it either.

2024-06-27 10:47 UTC, WULCAN commented on webapp/src/app/page.tsx
> -import HomeDashboard from '@/components/HomeDashboard';
This was the only use of HomeDashboard. Let's remove it now that we have inlined it on this page.

2024-06-27 10:47 UTC, WULCAN commented on webapp/src/app/page.tsx
> -  );
The old implementation has been moved, almost verbatim, to `api/projects/route.ts` with the only difference being that `ProjectCardProps` is replaced by `ProjectItem`. Those two types are exactly equal.

2024-07-03 18:17 UTC, henrycatalinismith commented
Time to delete this! Was just a proof of concept to grease the wheels of the conversation about architectural directions!

2024-07-03 18:17 UTC, closed without merging